# Generated by Django 5.1.3 on 2024-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nasc', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('nomeResp', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('escola', models.CharField(max_length=100)),
                ('anoEscolar', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
            ],
        ),
    ]
