# Generated by Django 5.1.3 on 2024-11-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='id',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
