# Generated by Django 5.1.3 on 2024-11-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_alter_crianca_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='pais',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='crianca',
            old_name='nomeResp',
            new_name='pai',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe uma criança cadastrada com este CPF.'}, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
