# Generated by Django 5.1.3 on 2024-11-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_rename_pais_crianca_mae_rename_nomeresp_crianca_pai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='pai',
            new_name='nomeResp',
        ),
        migrations.RenameField(
            model_name='crianca',
            old_name='mae',
            new_name='pais',
        ),
    ]
