# Generated by Django 5.1.3 on 2024-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_rename_pai_crianca_nomeresp_rename_mae_crianca_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe uma criança cadastrada com este CPF.'}, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='rg',
            field=models.CharField(max_length=12),
        ),
    ]
